### ISSUE TITLE
Missing textDirection.

### ISSUE THREAD

**Issue by inc16sec** [nelsonweze/rich_text_view#12]
Hello there. I was playing with this very helpfull and amazing library but then when I tried to add `textDirection` I found out that it is missing. Is there a way to implement it or is it something to wait for.

Here's what I'm expecting;

```dart
import 'package:intl/intl.dart' as intl;

bool isRTL(String text) {
  return intl.Bidi.detectRtlDirectionality(text);
}
  
  
RichTextView(
  text: text,
  textDirection: isRTL(text) ? TextDirection.rtl : TextDirection.ltr, //Missing
  align: isRTL(text) ? TextAlign.right : TextAlign.left,
  style: CustomTheme.postDescription,
),
```

`textDirection` is helpful when you have languages that read from right to left eg;(Arabic), so if you want to position them to the right side of the widget you check the language direction with the `isRTL` function, and then you set the `textDirection`.

I'm looking forward to hearing from you and thank you so much for the work and effort that you put into this wonderful library.
Best regards.

**Comment by nelsonweze** [comment]
Hi @inc16sec, added this in v1.0.0-dev-2

**Comment by inc16sec** [comment]
> Hi @inc16sec, added this in v1.0.0-dev-2

I can confirm. It is working as expected also `linkStyle` was added too which is something I was looking for.

Thank you so much @nelstein for your amazing work and quick response. Best regards.
