### ISSUE TITLE
remove top padding above textfield

### ISSUE THREAD

**Issue by saginbajracharya** [nelsonweze/rich_text_view#26]
unable to remove top padding above textField seem there is 16.0 top padding and also unable to change background color of a mention pop up container

**Comment by nelsonweze** [comment]
Hi, check `rich_text_view: ^1.1.0`
I have added the padding as a parameter, so you can easily use`EdgeInsets.zero` to remove
For the backgroundColor, I have set it to `Theme.cardColor`
