### ISSUE TITLE
Add more formatting

### ISSUE THREAD

**Issue by keanallen** [nelsonweze/rich_text_view#29]
Hi, I've been using this package in our chat application. This package is awesome and I think you should also consider text formatting like boling a text, italizing code formatting, etc.

Is this possible?

**Comment by nelsonweze** [comment]
Thank you @keanallen 

It's possible that there could be more default parsers as time goes on.  As from `rich_text_view: ^1.2.0-dev-1`, you can now extend the ParserType class and implement one that fits your needs exactly.
