### ISSUE TITLE
Words that are in-between with dot (.) are treated as url

### ISSUE THREAD

**Issue by keanallen** [nelsonweze/rich_text_view#30]
Any words that are in between with dot are treated as url. And when I click on the word, it opens a new browser.
![image](https://user-images.githubusercontent.com/45480782/185531708-1203b47c-6e70-450a-a454-74f3e34fc64b.png)

And when I clikc the "treated word as url":
![image](https://user-images.githubusercontent.com/45480782/185531762-916edf52-2539-4a1a-84fd-59000ac8b236.png)

**Comment by nelsonweze** [comment]
Hi, how would you like to identify what's a url? For some cases having google.com fits a url

**Comment by nelsonweze** [comment]
in `rich_text_view: ^1.2.0-dev-1`, you can define your own RegExp pattern to match specific websites or only urls with https.
