### ISSUE TITLE
TextEditingController was used after being disposed.

### ISSUE THREAD

**Issue by inc16sec** [nelsonweze/rich_text_view#32]
I'm using this package and providing my own TextEditingController into RichTextEditor. But when I Navigate out of the page I get the error below;

```
════════ Exception caught by hooks library ═════════════════════════════════════
The following assertion was thrown while disposing _Entry<HookState<dynamic, Hook<dynamic>>>:
A TextEditingController was used after being disposed.

Once you have called dispose() on a TextEditingController, it can no longer be used.
When the exception was thrown, this was the stack
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure>
package:flutter/…/foundation/change_notifier.dart:147
#1      ChangeNotifier.debugAssertNotDisposed
package:flutter/…/foundation/change_notifier.dart:154
#2      ChangeNotifier.dispose
package:flutter/…/foundation/change_notifier.dart:302
#3      _TextEditingControllerHookState.dispose
package:flutter_hooks/src/text_controller.dart:90
#4      HookElement.unmount
package:flutter_hooks/src/framework.dart:493
#5      _InactiveElements._unmount
package:flutter/…/widgets/framework.dart:1917
#6      _InactiveElements._unmount.<anonymous closure>
```

I'm using the `TextEditingController` from `flutter_hooks` which disposes automatically once it is not used.

My widget looks like this.

```dart
import 'package:flutter_hooks/flutter_hooks.dart';


Widget build(BuildContext context){
  final textEditingController = useTextEditingController();
  
  RichTextEditor(
    controller: textEditingController,
    onChanged: (value) {
        //I'm using the textEditingController here
    },
  ),
}
```

Looks like the issue is in the `text_editor.dart` file. The controller that is passed to the `RichTextEditor` is assigned to `TextEditingController` that is inside the `_RichTextEditorState` class. 

```dart
late TextEditingController controller;
late SuggestionController suggestionController;
  
@override
  void initState() {
    super.initState();
    controller = widget.controller ?? TextEditingController(text: widget.initialValue ?? '');
    suggestionController = (
      widget.suggestionController ?? SuggestionController()
    )..addListener(() {
      setState(() {});
    });
  }
```

And then once you pop out of the page the _RichTextEditorState's controller gets disposed and the error is thrown.

```dart
@override
  void dispose() {
    //This is what throws the error.
    controller.dispose();
    
    suggestionController.dispose();
    super.dispose();
  }
```

**Comment by keanallen** [comment]
Also getting this issue, have you solved this one master @inc16sec ?

**Comment by inc16sec** [comment]
> Also getting this issue, have you solved this one master @inc16sec ?

I delete the `controller.dispose();` line inside `dispose()` method. I don't know if it's the right thing to do, but for now it got rid of the error.

The `controller.dispose()` inside the `text_editor.dart` file.

**Comment by coderDove** [comment]
@nelsonweze basically same thing should be done for SuggestionsController as it is can be set outside TextEditor and should be disposed only if it is not existed. If nor - there will be same error about disposing but for suggestions controller.

Sent a PR if you are interested with this fix: https://github.com/nelsonweze/rich_text_view/pull/38

Regards,
Anton
