### ISSUE TITLE
RenderViewport does not support returning intrinsic dimensions.

### ISSUE THREAD

**Issue by keanallen** [nelsonweze/rich_text_view#39]
I got an error while typing "#" or "@".

My `RichTextEditor` is inside an `AlertDialog`

![image](https://user-images.githubusercontent.com/45480782/226271297-10a9305c-d3d5-4ed9-9000-bd46f0a4160d.png)

**Comment by nelsonweze** [comment]
Is this still an issue? @keanallen 
You might need to give the RichTextEditor a fixed size in this case.  Let me know if that helps.
