### ISSUE TITLE
Getting Data while select the mention from the MentionList

### ISSUE THREAD

**Issue by VimeshPolaris** [nelsonweze/rich_text_view#7]
Hii their!
I have an issue regarding getting data while selecting the mention from the list.
We can't get any kind of data or not found any callBack for performing an operation while selecting the mention.

**Comment by nelsonweze** [comment]
Hi, this seems like a good functionality to have. Let's see how soon I could add it.

**Comment by nelsonweze** [comment]
@VimeshPolaris  this feature has been added in [1.0.0-dev-1](https://pub.dev/packages/rich_text_view/versions/1.0.0-dev-1)
