### ISSUE TITLE
showMoreText not working

### ISSUE THREAD

**Issue by mariusbloemhof** [nelsonweze/rich_text_view#8]
Expected behavior:

showMoreText: false 

Should hide the .**..more** but it is still being displayed. Behavior is the same whether it is set to true or false

**Comment by nelsonweze** [comment]
I will try to see if I can reproduce this.

**Comment by nelsonweze** [comment]
@mariusbloemhof  the bug should be fixed in  [1.0.0-dev-1](https://pub.dev/packages/rich_text_view/versions/1.0.0-dev-1)
