### ISSUE TITLE
Bottom Overflowed By x Pixels

### ISSUE THREAD

**Issue by pitanni** [nelsonweze/rich_text_view#9]
Hi all,
I've created a list of suggestions I get from a query, but I get bottom overflowed. 
How to avoid this?

**Comment by nelsonweze** [comment]
Hi @pitanni  Could you provide a sample code? Hard to imagine where it's coming from.

**Comment by pitanni** [comment]
Sorry, my mistake. 
The error was due to another library.

Thanks @nelstein
